import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        <Link href='/user'>
          <h2>User</h2>
        </Link >
        <Link href='/blog'>
          <h2>Blog</h2>
        </Link>
        <Link href='/doc'>
          <h2>Docs</h2>
        </Link>
      </ul>
    </>
  );
}
