import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

export default function Home() {
  const router = useRouter();

  const handlerClick = () => {
    router.push("/user");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <button onClick={handlerClick}>Hello</button>
      <ul>
        <Link href="/user">
          <h2>User</h2>
        </Link>
        <Link href="/blog">
          <h2>Blog</h2>
        </Link>
        <Link href="/docs">
          <h2>Docs</h2>
        </Link>
      </ul>
    </>
  );
}
